<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PatientsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('patients')->delete();
        
        \DB::table('patients')->insert(array (
            0 => 
            array (
                'id' => 1,
                'hospital_no' => '0001',
                'user_id' => 2,
                'middlename' => 'Chinyere',
                'gender' => 'Female',
                'phone' => '0808 472 9310',
                'date_of_birth' => '1992-10-15',
                'religion_id' => 1,
                'marital_status' => 'divorced',
                'occupation' => 'Fashion Model',
                'state_of_residence' => 'Enugu',
                'lga_of_residence' => 'Owerri',
                'residential_address' => '68 Ogunwande Street',
                'state_of_origin' => 'Enugu',
                'lga_of_origin' => 'Jalingo',
                'tribe' => 'Kanuri',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:40',
                'updated_at' => '2025-06-01 18:12:40',
                'tag_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'hospital_no' => '0002',
                'user_id' => 3,
                'middlename' => 'Sekinat',
                'gender' => 'Male',
                'phone' => '08087858266',
                'date_of_birth' => '2016-09-20',
                'religion_id' => 1,
                'marital_status' => 'single',
                'occupation' => 'Segmental Paver',
                'state_of_residence' => 'Akwa Ibom',
                'lga_of_residence' => 'Katsina',
                'residential_address' => '86 David Street',
                'state_of_origin' => 'Sokoto',
                'lga_of_origin' => 'Damaturu',
                'tribe' => 'Tiv',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:40',
                'updated_at' => '2025-06-01 18:12:40',
                'tag_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'hospital_no' => '0003',
                'user_id' => 4,
                'middlename' => 'Aminu',
                'gender' => 'Male',
                'phone' => '+234 704 721 3151',
                'date_of_birth' => '2016-05-31',
                'religion_id' => 0,
                'marital_status' => 'single',
                'occupation' => 'Transportation Manager',
                'state_of_residence' => 'Borno',
                'lga_of_residence' => 'Umuahia',
                'residential_address' => '43 Aremu Street',
                'state_of_origin' => 'Kano',
                'lga_of_origin' => 'Akure',
                'tribe' => 'Fulani',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:40',
                'updated_at' => '2025-06-01 18:12:40',
                'tag_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'hospital_no' => '0004',
                'user_id' => 5,
                'middlename' => 'Chimamanda',
                'gender' => 'Male',
                'phone' => '+2348064813595',
                'date_of_birth' => '2013-03-15',
                'religion_id' => 0,
                'marital_status' => 'single',
                'occupation' => 'Building Inspector',
                'state_of_residence' => 'Gombe',
                'lga_of_residence' => 'Oshogbo',
                'residential_address' => '48 Balogun Street',
                'state_of_origin' => 'Ondo',
                'lga_of_origin' => 'Akure',
                'tribe' => 'Hausa',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:40',
                'updated_at' => '2025-06-01 18:12:40',
                'tag_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'hospital_no' => '0005',
                'user_id' => 6,
                'middlename' => 'Yakubu',
                'gender' => 'Male',
                'phone' => '0909 544 9343',
                'date_of_birth' => '1996-07-27',
                'religion_id' => 1,
                'marital_status' => 'divorced',
                'occupation' => 'Spraying Machine Operator',
                'state_of_residence' => 'Gombe',
                'lga_of_residence' => 'Port-Harcourt',
                'residential_address' => '92 Ademayowa Street',
                'state_of_origin' => 'Imo',
                'lga_of_origin' => 'Jos',
                'tribe' => 'Tiv',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:40',
                'updated_at' => '2025-06-01 18:12:40',
                'tag_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'hospital_no' => '0006',
                'user_id' => 7,
                'middlename' => 'Oluwunmi',
                'gender' => 'Male',
                'phone' => '08096236794',
                'date_of_birth' => '2000-10-26',
                'religion_id' => 1,
                'marital_status' => 'married',
                'occupation' => 'Carpenter Assembler and Repairer',
                'state_of_residence' => 'Abuja',
                'lga_of_residence' => 'Jos',
                'residential_address' => '92 Nwogu Street',
                'state_of_origin' => 'Kano',
                'lga_of_origin' => 'Yola',
                'tribe' => 'Hausa',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:41',
                'updated_at' => '2025-06-01 18:12:41',
                'tag_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'hospital_no' => '0007',
                'user_id' => 8,
                'middlename' => 'Augustina',
                'gender' => 'Male',
                'phone' => '+234 707 698 2823',
                'date_of_birth' => '2023-02-16',
                'religion_id' => 0,
                'marital_status' => 'divorced',
                'occupation' => 'Electronic Masking System Operator',
                'state_of_residence' => 'Ogun',
                'lga_of_residence' => 'Enugu',
                'residential_address' => '17 Onose Street',
                'state_of_origin' => 'Lagos',
                'lga_of_origin' => 'Katsina',
                'tribe' => 'Ibibio',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:41',
                'updated_at' => '2025-06-01 18:12:41',
                'tag_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'hospital_no' => '0008',
                'user_id' => 9,
                'middlename' => 'Simisola',
                'gender' => 'Male',
                'phone' => '0814 270 7563',
                'date_of_birth' => '1990-03-02',
                'religion_id' => 1,
                'marital_status' => 'married',
                'occupation' => 'Conveyor Operator',
                'state_of_residence' => 'Osun',
                'lga_of_residence' => 'Yenagoa',
                'residential_address' => '60 Ngozi Street',
                'state_of_origin' => 'Oyo',
                'lga_of_origin' => 'Uyo',
                'tribe' => 'Fulani',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:41',
                'updated_at' => '2025-06-01 18:12:41',
                'tag_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'hospital_no' => '0009',
                'user_id' => 10,
                'middlename' => 'Isioma',
                'gender' => 'Male',
                'phone' => '+2348052276088',
                'date_of_birth' => '2012-10-28',
                'religion_id' => 1,
                'marital_status' => 'single',
                'occupation' => 'Streetcar Operator',
                'state_of_residence' => 'Ondo',
                'lga_of_residence' => 'Abakaliki',
                'residential_address' => '85 Adegboye Street',
                'state_of_origin' => 'Enugu',
                'lga_of_origin' => 'Yola',
                'tribe' => 'Ibibio',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:41',
                'updated_at' => '2025-06-01 18:12:41',
                'tag_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'hospital_no' => '0010',
                'user_id' => 11,
                'middlename' => 'Wale',
                'gender' => 'Male',
                'phone' => '+2347039023554',
                'date_of_birth' => '2024-03-30',
                'religion_id' => 1,
                'marital_status' => 'single',
                'occupation' => 'Police Identification OR Records Officer',
                'state_of_residence' => 'Katsina',
                'lga_of_residence' => 'Lokoja',
                'residential_address' => '51 Olaoluwa Street',
                'state_of_origin' => 'Adamawa',
                'lga_of_origin' => 'Dutse',
                'tribe' => 'Ibibio',
                'hmo_id' => NULL,
                'dependent' => NULL,
                'principal_id' => NULL,
                'created_at' => '2025-06-01 18:12:42',
                'updated_at' => '2025-06-01 18:12:42',
                'tag_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'hospital_no' => '0011',
                'user_id' => 12,
                'middlename' => NULL,
                'gender' => 'Male',
                'phone' => '09031234567',
                'date_of_birth' => '1995-06-10',
                'religion_id' => 2,
                'marital_status' => 'Single',
                'occupation' => 'Civil Servant',
                'state_of_residence' => NULL,
                'lga_of_residence' => NULL,
                'residential_address' => NULL,
                'state_of_origin' => NULL,
                'lga_of_origin' => NULL,
                'tribe' => NULL,
                'hmo_id' => NULL,
                'dependent' => 'Yes',
                'principal_id' => NULL,
                'created_at' => '2025-06-10 08:23:00',
                'updated_at' => '2025-06-14 10:38:24',
                'tag_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'hospital_no' => '0012',
                'user_id' => 13,
                'middlename' => NULL,
                'gender' => 'Male',
                'phone' => '09031234567',
                'date_of_birth' => '1998-12-06',
                'religion_id' => NULL,
                'marital_status' => NULL,
                'occupation' => 'Civil Servant',
                'state_of_residence' => NULL,
                'lga_of_residence' => NULL,
                'residential_address' => NULL,
                'state_of_origin' => NULL,
                'lga_of_origin' => NULL,
                'tribe' => NULL,
                'hmo_id' => NULL,
                'dependent' => 'Yes',
                'principal_id' => NULL,
                'created_at' => '2025-06-12 11:36:11',
                'updated_at' => '2025-06-14 09:56:02',
                'tag_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'hospital_no' => '0013',
                'user_id' => 15,
                'middlename' => NULL,
                'gender' => 'Male',
                'phone' => '08165989386',
                'date_of_birth' => '2009-02-06',
                'religion_id' => 2,
                'marital_status' => 'Single',
                'occupation' => 'STUDENT',
                'state_of_residence' => 'Kano',
                'lga_of_residence' => 'Fagge',
                'residential_address' => NULL,
                'state_of_origin' => NULL,
                'lga_of_origin' => NULL,
                'tribe' => NULL,
                'hmo_id' => NULL,
                'dependent' => 'Yes',
                'principal_id' => NULL,
                'created_at' => '2025-06-24 15:32:35',
                'updated_at' => '2025-06-24 15:32:35',
                'tag_id' => NULL,
            ),
        ));
        
        
    }
}